import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  // ── ledger_snapshots ──────────────────────────────────────────────────
  // Daily closing balance per customer, generated by nightly job or on-demand.
  // Enables fast historical balance lookups without scanning entire ledger.
  await knex.schema.createTable('ledger_snapshots', (table) => {
    table.string('id', 36).primary();
    table.string('tenant_id', 36).notNullable().references('id').inTable('tenants');
    table.string('customer_id', 36).notNullable().references('id').inTable('customers');

    table.string('snapshot_date', 10).notNullable().comment('YYYY-MM-DD closing date');
    table.integer('closing_balance').notNullable().comment('Balance in paise at end of day');
    table.integer('total_debit').notNullable().defaultTo(0).comment('Sum of debits for the day');
    table.integer('total_credit').notNullable().defaultTo(0).comment('Sum of credits for the day');
    table.integer('entry_count').notNullable().defaultTo(0).comment('Number of ledger entries that day');

    table.timestamp('created_at').defaultTo(knex.fn.now());

    // One snapshot per customer per day
    table.unique(['tenant_id', 'customer_id', 'snapshot_date'], {
      indexName: 'uq_ledger_snapshot_daily',
    });
    table.index(['customer_id', 'snapshot_date'], 'idx_snapshot_customer_date');
  });

  // ── Add notes column to customer_ledger for adjustment descriptions ──
  await knex.schema.alterTable('customer_ledger', (table) => {
    table.text('notes').nullable().after('running_balance');
    table.string('created_by', 36).nullable().after('notes');
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('ledger_snapshots');
  await knex.schema.alterTable('customer_ledger', (table) => {
    table.dropColumn('notes');
    table.dropColumn('created_by');
  });
}
